version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: restaurant_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('raw', 'dim_restaurant')
                field: restaurant_key
      - name: driver_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('raw', 'dim_driver')
                field: driver_key
      - name: zone_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('raw', 'dim_zone')
                field: zone_key
      - name: date_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('raw', 'dim_date')
                field: date_key